/**
 * devcontainer.ts — Devcontainer probe, start, and config generation.
 */

import { execSync, spawn } from "node:child_process";
import { existsSync, writeFileSync, readFileSync, appendFileSync, openSync, closeSync, mkdirSync } from "node:fs";
import { join } from "node:path";

/** Fields we always inject into the override to ensure transparent path mounting. */
const WORKSPACE_OVERRIDES = {
  workspaceMount:
    "source=${localWorkspaceFolder},target=${localWorkspaceFolder},type=bind",
  workspaceFolder: "${localWorkspaceFolder}",
} as const;

/**
 * Find a devcontainer config at the project root.
 * Returns the path if found, null otherwise.
 */
export function findDevcontainerConfig(projectRoot: string): string | null {
  const candidates = [
    join(projectRoot, ".devcontainer", "devcontainer.json"),
    join(projectRoot, ".devcontainer.json"),
  ];

  for (const p of candidates) {
    if (existsSync(p)) return p;
  }

  return null;
}

/**
 * Generate .pi/devcontainer.override.json if not already present.
 *
 * Because --override-config REPLACES the entire devcontainer.json (it is not
 * merged on top of the workspace config), the override must be a complete,
 * valid config. We achieve this by:
 *   1. Reading the base devcontainer.json from the project.
 *   2. Stripping JSON comments (// and /* ... *\/) so JSON.parse succeeds.
 *   3. Overlaying our workspace-mount fields so paths inside the container
 *      match the host exactly (transparent mount).
 *   4. Writing the merged result as the override file.
 *
 * If the file already exists it is left untouched — the user may have
 * customised it. Also ensures .pi/devcontainer.override.json is in .gitignore.
 */
export function generateOverrideJson(projectRoot: string, configPath?: string, force = false): void {
  const overridePath = join(projectRoot, ".pi", "devcontainer.override.json");

  // If the file already exists, check whether it looks like the old 2-field
  // stub (only workspaceMount + workspaceFolder). If so, it was generated by
  // an older version of pi-dev-worktrees that used --override-config as a merge
  // target; now we know it REPLACES the base config, so the override must be
  // a complete, valid devcontainer config. Delete the stub so it is rebuilt.
  // When force=true (explicit /devcontainer on), always regenerate.
  if (existsSync(overridePath) && !force) {
    try {
      const existing = JSON.parse(readFileSync(overridePath, "utf8")) as Record<string, unknown>;
      const keys = Object.keys(existing);
      const isOldStub =
        keys.length === 2 &&
        keys.includes("workspaceMount") &&
        keys.includes("workspaceFolder");
      if (!isOldStub) return; // user-customised — leave it alone
      // else: fall through to regenerate
    } catch {
      return; // can't parse — leave it alone
    }
  }

  // Find base config if not supplied
  const baseConfigPath = configPath ?? findDevcontainerConfig(projectRoot);
  let base: Record<string, unknown> = {};

  if (baseConfigPath && existsSync(baseConfigPath)) {
    try {
      const raw = readFileSync(baseConfigPath, "utf8");
      // Strip single-line and multi-line comments so JSON.parse succeeds
      // (devcontainer.json commonly includes comments)
      const stripped = stripJsonComments(raw);
      base = JSON.parse(stripped) as Record<string, unknown>;
    } catch {
      // If parsing fails, fall back to workspace-overrides only.
      // The container startup will likely fail too, but the log will say why.
    }
  }

  const merged = { ...base, ...WORKSPACE_OVERRIDES };

  // If base devcontainer used the old "build.dockerfile" key, normalize to top-level dockerFile for CLI compatibility
  if ((merged as any).build && (merged as any).build.dockerfile && !(merged as any).dockerFile) {
    (merged as any).dockerFile = (merged as any).build.dockerfile;
  }
  // Ensure .pi directory exists before writing the override file
  try {
    const piDir = join(projectRoot, ".pi");
    if (!existsSync(piDir)) {
      mkdirSync(piDir, { recursive: true });
    }
  } catch {
    // Fall through — writeFileSync will throw a clearer ENOENT if mkdir fails
  }

  writeFileSync(overridePath, JSON.stringify(merged, null, 2) + "\n", "utf8");

  // Add to .gitignore if not present
  const gitignorePath = join(projectRoot, ".gitignore");
  const pattern = ".pi/devcontainer.override.json";
  let existing = "";

  if (existsSync(gitignorePath)) {
    existing = readFileSync(gitignorePath, "utf8");
    const lines = existing.split("\n");
    if (lines.some((l) => l.trim() === pattern)) return;
  }

  const separator = existing.endsWith("\n") || existing.length === 0 ? "" : "\n";
  appendFileSync(gitignorePath, `${separator}${pattern}\n`, "utf8");
}

/**
 * Strip // and /* ...*\/ comments from a JSON string so JSON.parse succeeds.
 * devcontainer.json often contains comments that standard JSON.parse rejects.
 */
export function stripJsonComments(json: string): string {
  // Remove multi-line comments
  let result = json.replace(/\/\*[\s\S]*?\*\//g, "");
  // Remove single-line comments (but not URLs like https://...)
  result = result.replace(/([^:])(\/\/[^\n]*)/g, "$1");
  // Also handle comment at start of line
  result = result.replace(/^\s*\/\/[^\n]*/gm, "");
  return result;
}

/**
 * Probe whether the devcontainer is running.
 * Returns true if the container responds within 10 seconds.
 * Uses a longer timeout than a quick health-check because `devcontainer exec`
 * can be slow on first invocation after the container has just started.
 */
export function probeContainer(projectRoot: string): boolean {
  const overridePath = join(projectRoot, ".pi", "devcontainer.override.json");
  try {
    const result = execSync(
      `devcontainer exec --workspace-folder ${shellQuote(projectRoot)} --override-config ${shellQuote(overridePath)} -- echo ok`,
      { timeout: 10_000, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] },
    );
    return result.trim().includes("ok");
  } catch {
    return false;
  }
}

/**
 * Read the startup outcome from .pi/devcontainer-up.log.
 *
 * `devcontainer up` prints a final JSON line on stdout:
 *   {"outcome":"success","containerId":"...", ...}
 *   {"outcome":"error","message":"...", ...}
 *
 * Returns the outcome string ("success", "error", or null if not yet written
 * or not parseable).
 */
export function readStartupOutcome(projectRoot: string): {
  outcome: "success" | "error" | null;
  message?: string;
  remoteWorkspaceFolder?: string;
  containerId?: string;
} {
  const logPath = containerLogPath(projectRoot);
  if (!existsSync(logPath)) return { outcome: null };
  try {
    const content = readFileSync(logPath, "utf8");
    // Scan from the end for a line that starts with '{' (the JSON summary line)
    const lines = content.trimEnd().split("\n");
    for (let i = lines.length - 1; i >= 0; i--) {
      const line = lines[i].trim();
      if (!line.startsWith("{")) continue;
      try {
        const parsed = JSON.parse(line) as Record<string, unknown>;
        if (parsed.outcome === "success") {
          return {
            outcome: "success",
            containerId: typeof parsed.containerId === "string" ? parsed.containerId : undefined,
            remoteWorkspaceFolder: typeof parsed.remoteWorkspaceFolder === "string"
              ? parsed.remoteWorkspaceFolder
              : undefined,
          };
        }
        if (parsed.outcome === "error") {
          return {
            outcome: "error",
            message: typeof parsed.message === "string" ? parsed.message : undefined,
          };
        }
      } catch {
        // not valid JSON, keep scanning
      }
    }
    return { outcome: null };
  } catch {
    return { outcome: null };
  }
}

/** Path where `devcontainer up` stdout/stderr is captured. */
export function containerLogPath(projectRoot: string): string {
  return join(projectRoot, ".pi", "devcontainer-up.log");
}

/**
 * List all running container IDs labeled with devcontainer.local_folder=<projectRoot>.
 * Returns an empty array if none found or on error.
 */
function listContainerIdsByLabel(projectRoot: string): string[] {
  try {
    const filter = `label=devcontainer.local_folder=${projectRoot}`;
    return execSync(`docker ps --quiet --filter ${shellQuote(filter)}`, {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
      timeout: 10_000,
    })
      .split("\n")
      .map(s => s.trim())
      .filter(Boolean);
  } catch {
    return [];
  }
}

/**
 * Find the first container ID by Docker label devcontainer.local_folder=<projectRoot>.
 * Returns undefined if none found.
 */
export function findContainerIdByLabel(projectRoot: string): string | undefined {
  return listContainerIdsByLabel(projectRoot)[0];
}

/**
 * Stop the devcontainer by stopping the Docker container whose ID was recorded
 * in the startup log. Falls back to stopping any containers labeled with
 * devcontainer.local_folder=<projectRoot>.
 * Errors are swallowed — stopping is best-effort.
 */
export function stopContainer(projectRoot: string): { stopped: boolean; containerId?: string; stoppedAllByLabel?: boolean } {
  const { containerId } = readStartupOutcome(projectRoot);
  if (containerId) {
    try {
      execSync(`docker stop ${shellQuote(containerId)}`, {
        stdio: "ignore",
        timeout: 30_000,
      });
      return { stopped: true, containerId };
    } catch {
      // Fall through to label-based stop if direct stop fails
    }
  }

  // Fallback: stop any containers created for this project (labeled by CLI)
  const ids = listContainerIdsByLabel(projectRoot);
  if (ids.length === 0) return { stopped: false };
  for (const id of ids) {
    try {
      execSync(`docker stop ${shellQuote(id)}`, { stdio: "ignore", timeout: 30_000 });
    } catch { /* ignore individual failures */ }
  }
  return { stopped: true, stoppedAllByLabel: true };
}

/**
 * Clear the startup log so a subsequent /devcontainer on always runs
 * `devcontainer up` fresh rather than short-circuiting on a stale outcome.
 */
export function clearStartupLog(projectRoot: string): void {
  const logPath = containerLogPath(projectRoot);
  if (existsSync(logPath)) {
    try {
      writeFileSync(logPath, "", "utf8");
    } catch { /* best-effort */ }
  }
}

/**
 * Build the argv array for `devcontainer up`.
 * Extracted so tests can assert on the exact flags without spawning a process.
 */
export function buildStartArgs(
  projectRoot: string,
  overridePath: string,
  removeExisting: boolean,
  noCache = false,
): string[] {
  const args = [
    "up",
    "--workspace-folder",
    projectRoot,
    "--override-config",
    overridePath,
  ];
  if (removeExisting) args.push("--remove-existing-container");
  if (noCache) args.push("--build-no-cache");
  return args;
}

/**
 * Start the devcontainer in the background (detached, fire-and-forget).
 * Stdout and stderr are written to .pi/devcontainer-up.log.
 *
 * @param removeExisting - Pass true to force-recreate the container even if
 *   one already exists (passes --remove-existing-container to devcontainer up).
 *   Use this when you need a clean start, e.g. after config changes or when
 *   a stale container from a previous session is suspected.
 */
export function startContainer(projectRoot: string, removeExisting = false, noCache = false): void {
  const overridePath = join(projectRoot, ".pi", "devcontainer.override.json");
  const logPath = containerLogPath(projectRoot);

  // Truncate log file before each new start attempt
  writeFileSync(logPath, `--- devcontainer up started at ${new Date().toISOString()} ---\n`, "utf8");

  const logFd = openSync(logPath, "a");
  const child = spawn(
    "devcontainer",
    buildStartArgs(projectRoot, overridePath, removeExisting, noCache),
    {
      detached: true,
      stdio: ["ignore", logFd, logFd],
      cwd: projectRoot,
    },
  );
  child.unref();
  closeSync(logFd);
}

/**
 * Return the last N lines of the devcontainer startup log, or an empty string
 * if no log exists yet.
 */
export function tailContainerLog(projectRoot: string, lines = 20): string {
  const logPath = containerLogPath(projectRoot);
  if (!existsSync(logPath)) return "";
  try {
    const content = readFileSync(logPath, "utf8");
    const allLines = content.trimEnd().split("\n");
    // Prefer only the most recent startup block, delimited by the header line we write before each start.
    const header = "--- devcontainer up started at ";
    let lastHeaderIdx = -1;
    for (let i = allLines.length - 1; i >= 0; i--) {
      if (allLines[i].startsWith(header)) { lastHeaderIdx = i; break; }
    }
    const recentBlock = lastHeaderIdx >= 0 ? allLines.slice(lastHeaderIdx) : allLines;
    return recentBlock.slice(-lines).join("\n");
  } catch {
    return "";
  }
}

/**
 * Shell-safe single-quote wrapping for path arguments.
 */
function shellQuote(s: string): string {
  return `'${s.replace(/'/g, "'\\''")}'`;
}
