/** Clone-local exclusion for every file or directory generated by this extension. */
import { execSync } from "node:child_process";
import { appendFileSync, existsSync, mkdirSync, readFileSync } from "node:fs";
import { dirname, isAbsolute, relative, resolve, sep } from "node:path";

export function generatedArtifactPattern(
  gitRoot: string,
  generatedPath: string,
  directory = false,
): string | null {
  const root = resolve(gitRoot);
  const target = resolve(generatedPath);
  const rel = relative(root, target);
  if (!rel || rel === ".." || rel.startsWith(`..${sep}`) || isAbsolute(rel)) return null;
  return `/${rel.split(sep).join("/")}${directory ? "/" : ""}`;
}

/** Best-effort: exclusion failures never block artifact generation. */
export function excludeGeneratedArtifact(
  gitRoot: string | undefined,
  generatedPath: string,
  directory = false,
): void {
  if (!gitRoot) return;
  const pattern = generatedArtifactPattern(gitRoot, generatedPath, directory);
  if (!pattern) return;
  try {
    const raw = execSync("git rev-parse --git-path info/exclude", {
      cwd: gitRoot,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    if (!raw) return;
    const excludePath = isAbsolute(raw) ? raw : resolve(gitRoot, raw);
    mkdirSync(dirname(excludePath), { recursive: true });
    const existing = existsSync(excludePath) ? readFileSync(excludePath, "utf8") : "";
    if (existing.split(/\r?\n/).some((line) => line.trim() === pattern)) return;
    const separator = existing.length === 0 || existing.endsWith("\n") ? "" : "\n";
    appendFileSync(excludePath, `${separator}${pattern}\n`, "utf8");
  } catch {
    // Valid for non-Git directories and unwritable Git metadata.
  }
}
